print("(-|-----|----|-----wifi hacking----|-----|---|--)")
print("(-|-----|----|----Wifi hacking-----|-----|---|---)")
print()
print("CrEaTeD bY //sAgoR//")
import time
print()
input("Type here wifi name: ")
print()
time.sleep(0.5)
input("Type 'start' to start the process: ")
print()
time.sleep(1)
print("Searching wifi......")
time.sleep(1)
print()
print("Making password")
print()
print("Attack start")
print()
print("34567 failed")
time.sleep(0.1)
print("45678 failed")
time.sleep(0.2)
print("34567 failed")
time.sleep(0.3)
print("45678 failed")
time.sleep(0.4)
print("34512 failed")
time.sleep(0.3)
print("45677 failed")
time.sleep(0.3)
print("45678 failed")
time.sleep(0.3)
print("56712 failed")
time.sleep(0.3)
print("67890 failed")
time.sleep(0.3)
print("89012 failed")
time.sleep(0.3)
print("56789 failed")
time.sleep(0.3)
print("567843 failed")
time.sleep(0.3)
print("567890 failed")
print()
print("Trying to break the password through alphabetical words: ")
print()
print("Nbdg failed")
print("zyshj failed")
print("tYuio failed")
print("cBof failed")
print("Abyuioz failed")
print("12Abgh2 •••connected••••")
print()
print(" !!!!!password found!!!!!")
print("password is: 12Abgh2")
time.sleep(0.5)
print("-----T--------H----A-----N----K----S----")

